package database.model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Facility.java
//  @ Date : 4/17/2014
//  @ Author : 
//
//




/** */
public class Facility extends Resource
{

	@Override
	public int getID() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void setID(int iD) {
		// TODO Auto-generated method stub
		
	}
}
