package reasoning;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractFactory.java
//  @ Date : 4/17/2014
//  @ Author : 
//
//




/** */
public class AbstractFactory{
	/** */
	public Policy createPolicy()
	{
		/**
		 * 1. open rule file
		 * 2. each line has the form: RULE_NAME WEIGHT PARAM1 PARAM2 ...
		 * 3. instantiate policy
		 * */
		return null;
	
	}
}
