package reasoning;

import database.model.Resource;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PolicyInstance.java
//  @ Date : 4/17/2014
//  @ Author : 
//
//




/** */
public class PolicyInstance
{
	/** */
	public boolean isViolated;
	
	/** */
	public Resource resource;
	
	/** */
	public Policy policy;
	
	/** */
	public void evaluate()
	{
		//set is violated
		isViolated = policy.evaluate(resource);
	}
}
