package reasoning;

import java.util.List;

import database.model.Resource;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PolicyManager.java
//  @ Date : 4/17/2014
//  @ Author : 
//
//




/** */
public class PolicyManager
{
	/** */
	public List<PolicyInstance> resourcePolicies;
	
	/** */
	public List<PolicyInstance> instantiatePolicies(List<Resource> r,  List<Policy> p)
	{
		//FACTORY PT INSTANTIEREA POLITICILOR
		//se itereaza resurse: res
		//se itereaza policiti: pol
		//daca sunt compatibile => add new PolicyResource(res, pol)
		//compatibilitate dupa clase => instanceof
		return resourcePolicies;
	
	}
	
	/** */
	public void evaluatePolicies()
	{
	//cheama evaluate pt fiecare
	}
	
	/** */
	public List<PolicyInstance> getViolatedPolicies()
	{
		//intoarece cele cu isViolate true
		return resourcePolicies;
	
	}
}
